### ISSUE TITLE
I want to add my repo to this

### ISSUE THREAD

**Issue by ice1000** [KotlinBy/awesome-kotlin#41]
https://github.com/ice1000/Dekoder

It is a desktop music player, not finished yet, but I`m going to make it awesome!

**Comment by ice1000** [comment]
@danielgomezrico @hotchemi @IRus @madhead @itrufeng 
I`m wondering a reply....

**Comment by IRus** [comment]
@ice1000 i will add it to new section "Desktop applications", thanks!

**Comment by ice1000** [comment]
@IRus :+1:

**Comment by ice1000** [comment]
@IRus and please review other issues.
They also want their projects to be added.
and here`s the Chinese edition of kotlin-docs: https://www.gitbook.com/book/wangjiegulu/kotlin-for-android-developers-zh/details

**Comment by IRus** [comment]
@ice1000 Now this repository contains some Russian articles(obviously, because i know Russian). I can add Chinese link too, but now i think to some separation of list to locale-specific link/articles. I even have ideas how to do it. I think i will implement these separation by next week, and than i will add these links.

**Comment by ice1000** [comment]
Get. tks
