### ISSUE TITLE
theoldreader doesn't like this RSS

### ISSUE THREAD

**Issue by gochev** [KotlinBy/awesome-kotlin#710]
Hey there I am using theoldreader since google reader stoped working. However for some reason both full and last 20 RSS are not working for them.

I have tweeted and send them a support email but I strongly believe the issue is not theirs since I have never ever had issue with other feed but http://kotlin.link/rss.xml just doesn't work.

**Comment by madhead** [comment]
A quick check shows multiple issues:

1. This RSS feed is actually an Atom feed, so instead of
    ```html
    <link rel="alternate" type="application/rss+xml" title="Kotlin.Link - 20 latest" href="/rss.xml"/>
    <link rel="alternate" type="application/rss+xml" title="Kotlin.Link - full archive" href="/rss-full.xml"/>
    ```  
    it should be
    ```html
    <link rel="alternate" type="application/atom+xml" title="Kotlin.Link - 20 latest" href="/rss.xml"/>
    <link rel="alternate" type="application/atom+xml" title="Kotlin.Link - full archive" href="/rss-full.xml"/>
    ```
1. `entries` are missing `updated` fields. The reader just don't have any information about the publication dates. There is only a global `updated` and `dc:date`, but they might not work with The Old Reader. Anyway, it's just wron: feed timestamp is not equal to entries timestamps
1. The feed is generated only for "Articles"; https://github.com/KotlinBy/awesome-kotlin/blob/373bd58fba3acee9f4c39f371caf964c42f78549/src/main/kotlin/link/kotlin/scripts/SiteGenerator.kt#L66-L72. As far as I see, there are no new articles on the site for a loooooong time. Basically, the last update [was two years ago](https://github.com/KotlinBy/awesome-kotlin/tree/main/articles). Since then, feed didn't change.

Question is: should we fix that at all? Is it an essential part of the site or could it be just sacrificed, having the fact it's stale for two years already…

**Comment by gochev** [comment]
I would love to have a working RSS since Kotlin is going strong this days and more and more stuff will be coming

**Comment by IRus** [comment]
Thank you @gochev and @madhead, I'll take care of this today

**Comment by gochev** [comment]
let us/me know when it is done so I can test it :)

**Comment by IRus** [comment]
@gochev please try now :)

**Comment by gochev** [comment]
http://kotlin.link/rss.xml still doesn't work

**Comment by IRus** [comment]
@gochev So w3c thinks that this are [valid feeds](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkotlin.link%2Frss.xml), I see requests from freshrss.org, inoreader.com (Neat User-Agent! `Mozilla/5.0 (compatible; inoreader.com; 10 subscribers`), feedbin as well (`Feedbin feed-id:1778771 - 3 subscribers`), but I don't see any request from theoldreader. I'm created an account there and trying it out – no luck. My tt-rss work well with this feed at the same time.

I'm sending an email to the theoldreader support, let's see if they can help with the issue.

**Comment by IRus** [comment]
Apparently, theoldreader using `FeedlyApp/1.0 (http://www.feedly.com)` user-agent, but anyway – no request from him to the updated feed. I'll wait a little until their cache expire

**Comment by IRus** [comment]
> Ruslan,
> 
> I am still looking into what could be going on with this feed.  I also tried to subscribe to it and found it could not get the URL yet the feed appears to be valid.  Once I know something I will update you.
> 
> Thanks for reaching out and thanks for using The Old Reader!

**Comment by IRus** [comment]
@gochev Issue seems resolved
